### ISSUE TITLE
Android emulator 7.0

### ISSUE THREAD

**Issue by MOcnarHusty** [xabaras/ARootPermissionsDetector#1]
Hi on standard android emulator 7.0  from google ,it detecting always root, can you check it ? Thank you!

**Comment by xabaras** [comment]
I'm having a look, meanwhile can you post the emulator configuration?
The more I know the sooner I can address the issue if any.
Thanks

**Comment by xabaras** [comment]
Just checked and on the android emulator SDK 24 it says "No root permissions detected" as expected.
![schermata 2017-06-07 alle 12 23 36](https://user-images.githubusercontent.com/1765044/26874032-51bc2328-4b7c-11e7-93e9-4bdd09e4793e.png)
Look forward to seeing your emulator configuration.

**Comment by MOcnarHusty** [comment]
Hi sorry for confusing, I have checked it again and it was API 25 which is causing issue 
The shortened emulator config is here:

CPU/ABI: Google APIs Intel Atom (x86_64)
Target: google_apis [Google APIs] (API level 25)
Skin: nexus_5
SD Card: 100M
hw.dPad: no
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5
vm.heapSize: 364
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.initialOrientation: Portrait
image.androidVersion.api: 25

Thank You!

**Comment by xabaras** [comment]
I've checked it and I've found that Build.TAGS contains "test-keys", a.k.a. you're on a test build, that's why the lib says it's rooted, because de facto you can access the device with root permissions. Open an adb shell and try yourself. You'll find that "su" command just works!
So, telling that's a rooted device is correct, don't you agree?

**Comment by MOcnarHusty** [comment]
Thank You I did the check, and su works and also I can list apps dir and access files so It can be considered as root.
